WITH W1 AS
 (SELECT T1.*
    FROM BASS_ODS.ODS_V_OPERATE_PROPROJECTINFO T1
   WHERE TO_CHAR(NVL(T1.REALDEALTIME, T1.PLANDEALTIME), 'YYYY') =
         TO_CHAR(SYSDATE, 'YYYY')
     AND BATCHNAME = '第1批次'
     AND (ISCOUNTDISCIPLINE <> '不计算' OR ISCOUNTDISCIPLINE IS NULL)),
W2 AS
 (SELECT W1.AREAID,
         W1.AREANAME,
         W1.BUID,
         W1.BUNAME,
         W1.ORGID,
         W1.ORGNAME,
         W1.PROID,
         W1.PRONAME,
         W1.COVERAREA,
         W1.ACREAGE,
         W1.AVAILABLEACREAGE,
         W1.TOTALVALUE,
         W1.SURPLUSVALUE,
         DECODE(NVL(W1.ACREAGE, 0), 0, 0, W1.TOTALVALUE / W1.ACREAGE) BITCHPRICE,
         NVL(W1.REALPLANNINGTIME, W1.PLANNINGTIME) PLANNINGTIME,
         ABS(NVL(W1.REALPLANNINGTIME, W1.PLANNINGTIME) -
             NVL(W1.REALDEALTIME, W1.PLANDEALTIME)) DIFFPLANNINGTIME,
         T1.PLANNING_POINTS,
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DEALTIME,
         NVL(W1.REALSTARTTIME, W1.PLANSTARTTIME) STARTTIME,
         NVL(W1.REALSTARTTIME, W1.PLANSTARTTIME) -
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DIFFSTARTTIME,
         T1.DELISTING_PLANNING,
         NVL(W1.REALPLANTIME, W1.PLANTIME) PLANTIME,
         NVL(W1.REALPLANTIME, W1.PLANTIME) -
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DIFFPLANTIME,
         T1.DELISTING_PROGRAMME,
         NVL(W1.REALDEMONSTRATIONTIME, W1.PLANDEMONSTRATIONTIME) DEMONSTRATIONTIME,
         NVL(W1.REALDEMONSTRATIONTIME, W1.PLANDEMONSTRATIONTIME) -
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DIFFDEMONSTRATIONTIME,
         T1.DELISTING_EMONSTRATION_PLO,
         NVL(W1.REALOPENINGTIME, W1.PLANOPENINGTIME) OPENINGTIME,
         NVL(W1.REALOPENINGTIME, W1.PLANOPENINGTIME) -
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DIFFOPENINGTIME,
         T1.DELISTING_OPENING,
         NVL(W1.REALCASHFLOWSBACKTIME, W1.PLANCASHFLOWSBACKTIME) CASHFLOWSBACKTIME,
         NVL(W1.REALCASHFLOWSBACKTIME, W1.PLANCASHFLOWSBACKTIME) -
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME) DIFFCASHFLOWSBACKTIME,
         T1.DELISTING_REFLOW
    FROM W1
    JOIN BASS_ODS.ODS_DISCIPLINE_BENCHMARKS T1
      ON W1.AREAID = T1.AREA_ORG_ID
   WHERE NVL(W1.REALPLANNINGTIME, W1.PLANNINGTIME) IS NOT NULL
     AND NVL(W1.REALDEALTIME, W1.PLANDEALTIME) IS NOT NULL
     AND NVL(W1.REALSTARTTIME, W1.PLANSTARTTIME) IS NOT NULL
     AND NVL(W1.REALPLANTIME, W1.PLANTIME) IS NOT NULL
     AND NVL(W1.REALDEMONSTRATIONTIME, W1.PLANDEMONSTRATIONTIME) IS NOT NULL
     AND NVL(W1.REALOPENINGTIME, W1.PLANOPENINGTIME) IS NOT NULL
     AND NVL(W1.REALCASHFLOWSBACKTIME, W1.PLANCASHFLOWSBACKTIME) IS NOT NULL
     AND NVL(W1.REALDEALTIME, W1.PLANDEALTIME) >=
         NVL(W1.REALPLANNINGTIME, W1.PLANNINGTIME)
     AND NVL(W1.REALSTARTTIME, W1.PLANSTARTTIME) >=
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME)
     AND NVL(W1.REALPLANTIME, W1.PLANTIME) >=
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME)
     AND NVL(W1.REALDEMONSTRATIONTIME, W1.PLANDEMONSTRATIONTIME) >=
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME)
     AND NVL(W1.REALOPENINGTIME, W1.PLANOPENINGTIME) >=
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME)
     AND NVL(W1.REALCASHFLOWSBACKTIME, W1.PLANCASHFLOWSBACKTIME) >=
         NVL(W1.REALDEALTIME, W1.PLANDEALTIME))
SELECT O.ORG_CLASSIFY, W2.*, SYSDATE
  FROM W2
  LEFT JOIN DIM_ORG O
    ON W2.AREAID = O.ORG_ID
